package com.etimaden.cResponseResult;

public class Urun_tag {
    public String isemri_kod = "";
    public String serino_kayit_id  = "";
    public String uretim_isemri_tipi  = "";
    public String uretim_isemri_tipi_alt  = "";
    public String isemri_detay_ID  = "";
    public String depo_kod  = "";
    public String urun_kod  = "";
    public String palet_agirligi  = "";
    public String palet_dizim_sayisi  = "";
    public String torba_agirlik  = "";
    public String karakteristikler  = "";
    public String depo_adi  = "";
    public String lotno = "";
    public String vardiya  = "";
    public String urun_adi  = "";
    public String aciklama  = "";
    public String rfid  = "";
    public String kod = "";
    public String palet_rfid  = "";
    public String isemri_sap_kod  = "";
    public String son_depo_kod  = "";
    public String son_depo_adi  = "";
    public String palet_kod  = "";
    public String islem_durumu  = "";
    public String etiket_turu  = "";
    public String kullanici_kod  = "";
    public String buffer_id  = "";
    public String kayıt_parametresi  = "";
    public String depo_silo_kod_list  = "";
    public String isletme  = "";
    public String isletme_alt  = "";
    public String isletme_esleme  = "";
    public String isletme_adi  = "";
    public String uretim_dakika_onayi = "";
    public String uretim_lot_sayi_kontol  = "";
    public String kilitli  = "";
    public String MAN_TİP  = "";
}
